### ISSUE TITLE
Afis module is missing

### ISSUE THREAD

**Issue by osvaldlaszlo** [asv-soft/asv-drones#212]
Hi,
The "asv-drones" project cannot be build, because the **Asv.Drones.Gui.Afis** module is missing from the solution.
Thanks

**Comment by asvol** [comment]
Hi.  This project is a proprietary plugin for the program. We are still developing the core of the program, so we have made several configurations for debugging plugins and libraries for ease of debugging. You can just switch to the develop branch and debug configuration. This configuration ignores any projects with plugins and should build.  We will be glad to help you if you fail.
<img width="1209" alt="image" src="https://github.com/asv-soft/asv-drones/assets/1770739/bd9c26e3-cf35-43f8-8d7e-4997bf63f561">

**Comment by osvaldlaszlo** [comment]
Hi,
Absolutely clear, thank you very much!
According to the information you provided, everything is already working.
