### ISSUE TITLE
Asv.Drones.Gui.Api Issues (Unable to compile)

### ISSUE THREAD

**Issue by Ghazanfar373** [asv-soft/asv-drones#320]
![Screenshot 2024-07-07 100609](https://github.com/asv-soft/asv-drones/assets/30001107/5ddd266c-8f92-4774-a453-9dca08b2df8b)

**Comment by asv-soft-u01** [comment]
Hello! Can you please provide more info on your issue? What branch are you on?

**Comment by Ghazanfar373** [comment]
Actually I was working on main branch clone. Is it the right branch to work on?

**Comment by Ghazanfar373** [comment]
Yes it is latest commit, crossed check

Could it be the reason of .NET8 ?

**Comment by asv-soft-u01** [comment]
No, the problem is that Visual Studio wants to get our API package with version 0.3.6 and it is probably not available via standard nuget download. I will try to resolve this issue today and then will get back to you.

**Comment by Ghazanfar373** [comment]
Thanks for your time and efforts !

**Comment by asv-soft-u01** [comment]
Please try to update your main branch and then to build the project.

**Comment by Ghazanfar373** [comment]
It's working now, Thanks A lot 👍
