### ISSUE TITLE
Fail to build GUI with breaking changes of Asv.Mavlink 3.10.2

### ISSUE THREAD

**Issue by nivedano** [asv-soft/asv-drones#327]
If get the `asv.mavlink` updated from 3.10.0 to the latest 3.10.2, the build fails.

`Asv.Drones.Gui\Services\Mavlink\MavlinkDevicesService.cs`

`CS1503	Argument 3: cannot convert from 'Asv.Mavlink.RfsaClientDeviceConfig' to 'Asv.Mavlink.RsgaClientDeviceConfig'`
![image](https://github.com/user-attachments/assets/6332ec39-d04f-4bc0-818d-0a30ea8c2369)

where
`Asv.Drones.Gui\Services\Mavlink\MavlinkDevicesService.cs`
![image](https://github.com/user-attachments/assets/c98126c5-2b4c-474e-9b09-80499d7acda7)

fails `Asv.Drones.Gui\Services\Mavlink\MavlinkDevicesService.cs 3.10.2`
![image](https://github.com/user-attachments/assets/39aff393-e5f3-4913-9a59-d7a85c536b29)

works `Asv.Drones.Gui\Services\Mavlink\MavlinkDevicesService.cs 3.10.0`
![image](https://github.com/user-attachments/assets/414d3eb8-a02b-4837-bc5a-c69b827f919a)

**Comment by asv-soft-u01** [comment]
Hello!

That is indeed the case. Current develop and main branches should use mavlink v3.10.0. Do you need something specific from the new mavlink version that is not supported in 3.10.0?

Best regards,
Aleksandr.

**Comment by nivedano** [comment]
I don't think so, it's rather for purity's sake arvthe moment. The inconsistrncy in the code is obvious and the fix seems easy. 11:00, 2 августа 2024 г., Aleksandr ***@***.***>:
Hello!
That is indeed the case. Current develop and main branches should use mavlink v3.10.0. Do you need something specific from the new mavlink version that is not supported in 3.10.0?
Best regards,
Aleksandr.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by asv-soft-u01** [comment]
Develop branch has been updated and now supports Asv.Mavlink v3.10.2.

Best regards,
Aleksandr
