### ISSUE TITLE
Can we connect multiple vehicles using different datagram ports?

### ISSUE THREAD

**Issue by Ghazanfar373** [asv-soft/asv-drones#354]
Hi,  I really impressed by your ongoing progress on this repo . I just want to know can we connect multiple vehicles using different UDP ports?

**Comment by asvol** [comment]
Hi, thanks for your feedback! Yes, you can indeed add multiple ports of various types, including serial ports, TCP, and UDP. The key is to ensure that each vehicle has a unique SYS/COM_ID and to avoid creating circular references, as there’s currently no protection against that. I only had access to Arducopter’s SITL, so the screenshot shows TCP ports. However, you can add UDP ports in the same way.

![image](https://github.com/user-attachments/assets/9acb2dfb-ea28-4a19-b02b-1210271dc4d8)

![image](https://github.com/user-attachments/assets/763d0d47-3bbd-4a36-ae8e-96abedc28b2a)
